/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 4, 2022 at 8:33:40 PM Central Standard Time
* Operating System: Version 11.6 (Build 20G165)
* Image Source: /System/Library/Frameworks/NetworkExtension.framework/Versions/A/NetworkExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NEFilterProviderConfiguration;

@interface NEContentFilter : NSObject <NSCopying> {
    char _enabled;
    char _enableManualMode;
    NEFilterProviderConfiguration* _provider;
    long long _grade;
}

@property (assign) char enableManualMode;                               //@synthesize enableManualMode=_enableManualMode - In the implementation block
@property (getter=isEnabled) char enabled;                              //@synthesize enabled=_enabled - In the implementation block
@property (copy) NEFilterProviderConfiguration * provider;              //@synthesize provider=_provider - In the implementation block
@property (assign,nonatomic) long long grade;                           //@synthesize grade=_grade - In the implementation block
-(id)init;
-(void)setEnabled:(char)arg1 ;
-(char)isEnabled;
-(NEFilterProviderConfiguration *)provider;
-(long long)grade;
@end

