/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 4, 2022 at 8:33:40 PM Central Standard Time
* Operating System: Version 11.6 (Build 20G165)
* Image Source: /System/Library/Frameworks/NetworkExtension.framework/Versions/A/NetworkExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cocoa/Cocoa.h>
#import "NEConfiguration.h"

@protocol OS_dispatch_queue;
@class NSObject, NSDictionary;

@interface NEConfigurationManager : NSObject {
	NSDictionary* _loadedConfigurations;
}

//+(id)sharedManager;
+(NEConfigurationManager *)sharedManager;
-(NSDictionary *)loadedConfigurations;
@property (retain) NSDictionary * loadedConfigurations;                                //@synthesize loadedConfigurations=_loadedConfigurations - In the implementation block
-(char)reloadFromDisk;
@end

