/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 4, 2022 at 8:33:40 PM Central Standard Time
* Operating System: Version 11.6 (Build 20G165)
* Image Source: /System/Library/Frameworks/NetworkExtension.framework/Versions/A/NetworkExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import "NEProfilePayloadHandlerDelegate.h"

@class NSUUID, NSString, NEContentFilter, NEVPN, NEDNSProxy, NEProfileIngestionPayloadInfo;

@interface NEConfiguration : NSObject <NEProfilePayloadHandlerDelegate> {
    long long _grade;
    NSUUID* _identifier;
    NSString* _application;
    NSString* _name;
    NSString* _applicationName;
    NSString* _applicationIdentifier;
    NSString* _externalIdentifier;
    NEProfileIngestionPayloadInfo* _payloadInfo;
    NEContentFilter* _contentFilter;
    NEVPN* _VPN;
    NEDNSProxy* _dnsProxy;
    long long _appPermissionType;
}

@property (readonly) NSString * pluginType;
@property (assign,nonatomic) long long appPermissionType;                  //@synthesize appPermissionType=_appPermissionType - In the implementation block
@property (readonly) long long grade;                                      //@synthesize grade=_grade - In the implementation block
@property (readonly) NSUUID * identifier;                                  //@synthesize identifier=_identifier - In the implementation block
@property (copy) NSString * application;                                   //@synthesize application=_application - In the implementation block
@property (copy) NSString * name;                                          //@synthesize name=_name - In the implementation block
@property (copy) NSString * applicationName;                               //@synthesize applicationName=_applicationName - In the implementation block
@property (copy) NSString * applicationIdentifier;                         //@synthesize applicationIdentifier=_applicationIdentifier - In the implementation block
@property (copy) NSString * externalIdentifier;                            //@synthesize externalIdentifier=_externalIdentifier - In the implementation block                                        //@synthesize appVPN=_appVPN - In the implementation block
@property (copy) NEContentFilter * contentFilter;                          //@synthesize contentFilter=_contentFilter - In the implementation block                                   //@synthesize appPush=_appPush - In the implementation block
@property (copy) NEVPN * VPN;
@property (copy) NEDNSProxy * dnsProxy;                          //@synthesize dnsProxy=_dnsProxy - In the implementation block                                   //@synthesize appPush=_appPush - In the implementation block
@property (copy) NEProfileIngestionPayloadInfo * payloadInfo;              //@synthesize payloadInfo=_payloadInfo - In the implementation block
+(void)addError:(id)arg1 toList:(id)arg2 ;
-(id)getConfigurationIdentifier;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSUUID *)identifier;
-(NSString *)applicationIdentifier;
-(NSString *)application;
-(NEContentFilter *)contentFilter;
-(NEVPN *)VPN;
-(NEDNSProxy *)dnsProxy;
-(NEProfileIngestionPayloadInfo *)payloadInfo;
@end

