/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 4, 2022 at 8:33:41 PM Central Standard Time
* Operating System: Version 11.6 (Build 20G165)
* Image Source: /System/Library/Frameworks/NetworkExtension.framework/Versions/A/NetworkExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSArray, NEVPNProtocol;

@interface NEVPN : NSObject <NSCopying> {

	char _enabled;
	char _onDemandEnabled;
	char _disconnectOnDemandEnabled;
	char _onDemandUserOverrideDisabled;
	NSArray* _onDemandRules;
	NEVPNProtocol* _protocol;
	long long _tunnelType;
	NSArray* _exceptionApps;

}

@property (copy) NSArray * exceptionApps;                                                                          //@synthesize exceptionApps=_exceptionApps - In the implementation block
@property (getter=isEnabled) char enabled;                                                                         //@synthesize enabled=_enabled - In the implementation block
@property (getter=isOnDemandEnabled) char onDemandEnabled;                                                         //@synthesize onDemandEnabled=_onDemandEnabled - In the implementation block
@property (assign,getter=isDisconnectOnDemandEnabled,nonatomic) char disconnectOnDemandEnabled;                    //@synthesize disconnectOnDemandEnabled=_disconnectOnDemandEnabled - In the implementation block
@property (assign,getter=isOnDemandUserOverrideDisabled,nonatomic) char onDemandUserOverrideDisabled;              //@synthesize onDemandUserOverrideDisabled=_onDemandUserOverrideDisabled - In the implementation block
@property (copy) NSArray * onDemandRules;                                                                          //@synthesize onDemandRules=_onDemandRules - In the implementation block
@property (copy) NEVPNProtocol * protocol;                                                                         //@synthesize protocol=_protocol - In the implementation block
@property (assign) long long tunnelType;                                                                           //@synthesize tunnelType=_tunnelType - In the implementation block
-(char)checkValidityAndCollectErrors:(id)arg1 ;
-(char)isOnDemandUserOverrideDisabled;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(id)init;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(char)isEnabled;
-(NEVPNProtocol *)protocol;
-(long long)tunnelType;
-(id)copyLegacyDictionary;
-(char)isOnDemandEnabled;
-(char)isDisconnectOnDemandEnabled;
-(NSArray *)exceptionApps;
-(id)descriptionWithIndent:(int)arg1 options:(unsigned long long)arg2 ;
-(id)initFromLegacyDictionary:(id)arg1 ;
-(NSArray *)onDemandRules;
@end

